### ISSUE TITLE
Poly-Subtract Issue

### ISSUE THREAD

**Issue by ManuelaKM** [konantian/CMPUT325-TestCases#1]
The arguments in test cases 5.1.11 to 5.1.13 are incorrect because they are not in normal form.

(test-case '5.1.11
    (poly-subtract '((4 . 2) (3 . 1) (2 . 1) (1 . 0)) 
                   '((4 . 2) (3 . 1) (2 . 1) (1 . 0)))
    NIL
)

should be

(test-case '5.1.11
    (poly-subtract '((4 . 2) (5 . 1)  (1 . 0)) 
                   '((4 . 2) (5 . 1)  (1 . 0)))
    NIL
)

**Comment by konantian** [comment]
They did escape from my attention, thanks so much for point out!
